version: '2'
services:
  web:
      build: ./
      ports:
          - "8080:80"
      depends_on:
          - php
  php:
      image: php:7-fpm
      volumes:
          - ./www:/usr/share/nginx/html/